runtime: nodejs16

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /(.*)
  static_files: \1
  upload: (.*)

env_variables:
  GCLOUD_ACCESS_TOKEN: "$(gcloud auth print-access-token)"
